config/routes.rb
MyKeyboards::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :keyboards
  end

  get '/keyboards/select' => 'keyboards#select'

  resources :keyboards do
    resources :keys
  end

  root "welcome#index"

end

app/models/key.rb
class Key < ActiveRecord::Base
  belongs_to :keyboard
  validates :frequency, :wave, :panner, :delay, :note_filter, :volume, :key_code, :presence => true
end

app/models/keyboard.rb
class Keyboard < ActiveRecord::Base
  belongs_to :user
  has_many :keys
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :keyboards         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/keyboards_controller.rb
class KeyboardsController < ApplicationController

  def index
    # @keyboard = Keyboard.find(params[:id])
  end

  def new
    @keyboard = Keyboard.new
  end

  def create
    @keyboard = current_user.keyboards.new(keyboard_params)

    if @keyboard.save
      flash[:notice] = "New keyboard created"
      redirect_to @keyboard
    else
      @errors = @keyboard.errors.messages
      render "new"
    end
  end

  def select
    if request.xhr?
      if params[:selection] == "0"
        render "_low_c_keyboard", :layout => false
      elsif params[:selection] == "1"
        render "_middle_c_keyboard", :layout => false
      elsif params[:selection] == "2"
        render "_middle_high_c_keyboard", :layout => false
      elsif params[:selection] == "3"
        render "_high_c_keyboard", :layout => false
      end
    end
  end

  def show
    @keyboard = Keyboard.find(params[:id])
  end

  private

  def keyboard_params
    params.require(:keyboard).permit(:name)
  end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  
  def new
  	@keyboard = Keyboard.find(params[:keyboard_id])
    @key = Key.new  
  end

  def create
    @keyboard = Keyboard.find(params[:keyboard_id])
    @key = @keyboard.keys.new(key_params)
    
    p @key
    
    if @key.save
      flash[:notice] = "Key created"
      redirect_to keyboard_path(@keyboard)
    else
      @errors = @key.errors.messages
      flash[:notice] = "Fuck off"
      render "new"
    end
  end

  private

  def key_params
    params.require(:key).permit(:frequency, :wave, :panner, :delay, :note_filter, :volume, :key_code)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keyboards_helper.rb
module KeyboardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/keyboards/_form.html.erb
<%= form_for @keyboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %> 
<% end %>

app/views/keyboards/index.html.erb
<div id="center_options">
  <form id="choose_keyboard" action="/keyboards/select" method="GET">
    <select name="keyboard_selector" id="keyboard_selector">
      <option selected="selected">Please choose your keyboard...</option>
      <option value="0">Low C</option>
      <option value="1">Middle C</option>
      <option value="2">Middle High C</option>
      <option value="3">High C</option>
    </select>
  </form>

    <select name="wave_selector" id="wave_selector">
      <option selected="selected">Please select here to make all key tones the same...</option>
      <option value="0">Sine</option>
      <option value="1">Square</option>
      <option value="2">Sawtooth</option>
      <option value="3">Triangle</option>
    </select>
    <br>
    <select name="pan_selector" id="pan_selector">
      <option selected="selected">Please select here to pan the sound to one side...</option>
      <option value="0">L</option>
      <option value="1">R</option>
    </select>
</div>

<div id="keyboard_location">
</div>

<script type="text/javascript">

  $(document).on('change', '#keyboard_selector', function(event) {
    event.preventDefault();

    var selected = $('#keyboard_selector').val();
    var url = $('#choose_keyboard').attr('action');

    $.get(url, {selection: selected}, function(serverResponse) {
      $('#keyboard_location').html(serverResponse);
    })
  });//

  $(document).ready(function() {

    $("#wave_selector").change(function() {

        var val = $(this).val();

        if (val == "0") {
          for (var i = 1; i <= 18; i++) {
            $("#wave_" + i).html("<option value='0'>Sine</option><option value='1'>Square</option><option value='2'>Sawtooth</option><option value='3'>Triangle</option>")
          }
        } else if (val == "1") {
          for (var i = 1; i <= 18; i++) {
            $("#wave_" + i).html("<option value='1'>Square</option><option value='0'>Sine</option><option value='2'>Sawtooth</option><option value='3'>Triangle</option>")
          }
        } else if (val == "2") {
          for (var i = 1; i <= 18; i++) {
            $("#wave_" + i).html("<option value='2'>Sawtooth</option><option value='1'>Square</option><option value='0'>Sine</option><option value='3'>Triangle</option>")
          }
        } else if (val == "3") {
            for (var i = 1; i <= 18; i++) {
            $("#wave_" + i).html("<option value='3'>Triangle</option><option value='0'>Sine</option><option value='1'>Square</option><option value='2'>Sawtooth</option>")
          }
        }
    });

    $("#pan_selector").change(function() {

        var val = $(this).val();

        if (val == "0") {
          for (var i = 1; i <= 18; i++) {
            console.log("here");
            $("#panner_" + i).attr('value', '-3');
          }
        } else if (val == "1") {
          for (var i = 1; i <= 18; i++) {
            $("#panner_" + i).attr('value', '3');
          }
        }
    });

  });





</script>

app/views/keyboards/new.html.erb
<h1>Add a keyboard</h1>

<%= render "keyboards/form" %>

app/views/keyboards/show.html.erb
<h1><%= @keyboard.name %></h1>

<%= link_to "Add a key", new_keyboard_key_path(@keyboard) %>

<div class="row">
	<% @keyboard.keys.each_with_index do |k, index| %>
	  <div class="col-xs-12 col-md-3 key">
	  	<div>Key <%= index + 1 %></div>
		  <div id="freq-<%= index %>">
		  	<p>Frequency: <span><%= k.frequency %></span></p>
		  </div>

		  <div id="wave-<%= index %>">
		  	<p>Wave: <span><%= k.wave %></span><p>
		  </div>

		  <div id="panner-<%= index %>">
		  	<p>Panner: <span><%= k.panner %></span><p>
		  </div>

		  <div id="delay-<%= index %>">
		  	<p>Delay: <span><%= k.delay %></span><p>
		  </div>

		  <div id="filter-<%= index %>">
		  	<p>Filter: <span><%= k.note_filter %></span><p>
		  </div>

		  <div id="volume-<%= index %>">
		  	<p>Volume: <span><%= k.volume %></span><p>
		  </div>

		  <div id="keycode-<%= index %>">
		  	<p>Key Code: <span><%= k.key_code %></span><p>
		  </div>
		</div>
	<% end %>
</div>

app/views/keys/_form.html.erb
<% if @errors %>
  <%= @errors %>
<% end %>

<%= form_for [@keyboard, @key] do |f| %>
  <div id="frequency">Frequeny: <span></span>
    <%= f.range_field :frequency, {min: "50", max: "5000", step: "0.1", id: "freq"}%>
  </div>

  <div id="wave-type">Wave Type:
    <%= f.select :wave, ["sine", "square", "sawtooth", "triangle"] %>
  </div>

  <div id="panner">Panner: <span></span>
    <%= f.range_field :panner, {min: "-3", max: "3", step: "0.01", id: "pan"} %>
  </div>

  <div id="delay">Delay: <span></span>
    <%= f.range_field :delay, {min: "0", max: "1", step: "0.01", id: "d-lay"} %>
  </div>

  <div id="note_filter">Filter: <span></span>
    <%= f.range_field :note_filter, {min: "-4800", max: "4800", step: "0.01", id: "fil"} %>
  </div>

  <div id="volume">Volume: <span></span>
    <%= f.range_field :volume, {min: "0", max: "1", step: "0.1", id: "vol"} %>
  </div>

  <div id="key-code">
    <%= f.label :key_code %>
    <%= f.select :key_code, [["A", 65], ["S", 83], ["D", 68], ["F", 70], ["J", 74], ["K", 75], ["L", 76], [";", 186]] %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

<script>

  $("#freq").on("click", function(){
    var freq = $(this).val();
    $("#frequency span").html(freq);
  })

  $("#pan").on("click", function(){
    var panner = $(this).val();
    $("#panner span").html(panner);
  })

  $("#d-lay").on("click", function(){
    var delay = $(this).val();
    $("#delay span").html(delay);
  })

  $("#fil").on("click", function(){
    var filter = $(this).val();
    $("#note_filter span").html(filter);
  })

  $("#vol").on("click", function(){
    var volume = $(this).val();
    $("#volume span").html(volume);
  })
</script>

app/views/keys/new.html.erb
<%= render "keys/form" %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Keyboard Fun!", root_path, :class => "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyKeyboards</title>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= render "layouts/messages" %>
	<%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Keyboard</h1>

<% if current_user %>
  <%= link_to "Add A Keyboard", new_keyboard_path %>
<% end %>